pipeline {
    agent any
    tools {
        nodejs 'NodeJS 8.10.0'
    }
    environment {
        AWS_PROFILE = sh(script: 'aws iam list-account-aliases | jq -jr .AccountAliases[0]', returnStdout: true)
        echo "Profile: ${AWS_PROFILE}"
    }
    parameters {
        choice(choices: 'us-east-1', description: 'What AWS region?', name: 'AWS_DEFAULT_REGION')
    }
    stages {

        stage('Setup') {
            steps {
                echo 'Running red Jenkinsfile...'
            }
        }
    }
}