pipeline {
     agent { label 'docker' }
    tools {
        nodejs 'NodeJS 8.10.0'
    }
    parameters {
        choice(choices: 'us-east-1', description: 'What AWS region?', name: 'AWS_DEFAULT_REGION')
    }
    stages {

        stage('Setup') {
            steps {
                echo 'Running green Jenkinsfile...'
            }
        }
    }
}